### ISSUE TITLE
Add foundation for displaying data of entities themselves

### ISSUE THREAD

**Issue by versusbassz** [versusbassz/entity-viewer#15]
The quite large task. Added a project for that: https://github.com/versusbassz/wp-meta-viewer/projects/2

## Sub-tasks
- [x] refactor backend of meta fields to a Fetcher-class
- [x] "mysql" order for entity props
    - [x] Fix visual problems (the width and wrapping of the "DB order" column in different situations)
- [x] memorize a chosen tab (by entity type, stored in localStorage as a json hashmap)
    - [x] TTL for stored value --- See: #62 
- [x] Improve displaying of tabs/sections names (human readable names, not ids)
- [x] to do smth with `post_content` (related to #2)
- [x] Handle wp_errors on the backend properly + display them on frontend

## Misc
- [x] add an issue for better displaying of terms (maybe, several tables in one `entity` tab) --- See: #51 
- [x] custom order (more convenient) for props of posts (to a separate issue) --- See: #52

**Comment by versusbassz** [comment]
Most of the task has been done. Several sub-tasks left (polishing).

**Comment by versusbassz** [comment]
Done. This is a big step forward :cake:
