### ISSUE TITLE
Release on wordpress.org

### ISSUE THREAD

**Issue by versusbassz** [versusbassz/entity-viewer#8]
## Sub-tasks

- [x] chose a new name for the plugin --- see the comment below
- [x] comment-tags in the entry PHP-file ([docs](https://developer.wordpress.org/plugins/plugin-basics/header-requirements/))
- readme.txt ([sample](https://wordpress.org/plugins/readme.txt), [docs-1](https://developer.wordpress.org/plugins/wordpress-org/), [docs-2](https://wordpress.org/plugins/developers/))
    - [x] by Vladimir Sklyar + link
    - [x] main section
    - [x] changelog
- [x] rephrase admin noticies (display current/minimal versions)
- [x] license
- [x] a note about versioning (semver)

**Comment by versusbassz** [comment]
The new name of the plugin has been chosen in #30:
- visual name (on wp.org plugin's page - h1): `Entity Viewer`
- wp.org slug: `entity-viewer`
- github repo slug: `entity-viewer`

**Comment by versusbassz** [comment]
The repo's name has been changed: `wp-meta-viewer` -> `entity-viewer`

**Comment by versusbassz** [comment]
The plugin (v0.3.1) was sent to wp.org for the review. Waiting...

![entity-viewer-0 3 1-sent](https://user-images.githubusercontent.com/2342074/150515039-712b57f6-62d3-4475-a90f-8c7a7d1f4f6e.png)

**Comment by versusbassz** [comment]
To fix after 1st review
- [ ] prefix for functions in global namespace: vsm - > entv / envw / entvw
- [ ] don't copy GET to variable

**Comment by versusbassz** [comment]
Fixed the issues.  
Release [0.4.0](https://github.com/versusbassz/entity-viewer/milestone/9?closed=1) version  
Sent the new version of the plugin via email to the moderation team.  
Waiting for results...

**Comment by versusbassz** [comment]
Done! It has been approved. I did it :)
> * SVN URL: https://plugins.svn.wordpress.org/entity-viewer
> * Public URL: https://wordpress.org/plugins/entity-viewer

Now working on #22 to automate the releasing process
